# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friend',
            field=models.ManyToManyField(related_name='_user_friend_+', to='belt_app.User'),
        ),
    ]
